### ISSUE TITLE
output data of your experiment

### ISSUE THREAD

**Issue by li-jing-wen** [mingkaid/rl-prompt#18] opened 2023-02-16 03:04 UTC
I need to do some comparative experiments. Could you please provide the final output data of your experiment?

**Comment by mingkaid** [comment] 2023-02-16 03:05
Thank you for your interest. What task and dataset are you trying to compare?

**Comment by li-jing-wen** [comment] 2023-02-16 03:08
> Thank you for your interest. What task and dataset are you trying to compare?
Thank you for your help!
I want to compare the results of the YELP dataset in the text style transfer task.

**Comment by mingkaid** [comment] 2023-02-16 03:21
Sure. We might need a few days to reproduce the setting described in the paper. Once we're done we'll update our repo. I'll close this issue for now because the question has been addressed.

**Closed by mingkaid** 2023-02-16 03:21 UTC

**Comment by mingkaid** [comment] 2023-02-21 15:37
Hi, quick update that we have uploaded the final output for the Yelp dataset in the text style transfer task. You can find it at `example/text-style-transfer/test_outputs`. 

We uploaded both the original GPT-2 format (`clean`) and the typical space-delimited format (`raw`). We evaluated everything with the `clean` format, but if you were comparing with other outputs/references in the typical format, `raw` may be more consistent. 

Let us know if you have any questions. Best of luck with your project!
